In [39]:
import pyforest
from sklearn.cluster import KMeans

In [40]:
features = np.array([[1,2],[2,2],[1,4],[2,4],[1,6],[4,2],[4,4],[5,2],[5,4],[4.5,6]])

In [41]:
model = KMeans(n_clusters=2)

In [42]:
model.fit(features)

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
    n_clusters=2, n_init=10, n_jobs=None, precompute_distances='auto',
    random_state=None, tol=0.0001, verbose=0)

In [43]:
model.labels_

array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1])

In [44]:
features[0]

array([1., 2.])

In [45]:
model.labels_[0]

0

In [46]:
model.cluster_centers_

array([[1.4, 3.6],
       [4.5, 3.6]])

In [47]:
model.predict([[3.5,2]])

array([1])