In [2]:
import numpy as np

#CREATING AN ARRAY OF NUMBERS IN A MATRIX FORM

mat1 = np.array([ [0,1,2],[3,4,5],[6,7,8] ])

print(mat1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [5]:
#CREATING A MATRIX WITH THE 'arange' FUNCTION

x = np.arange(1,10)
y = x.reshape(3,3)

print(y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [16]:
#ADDING AND MULTIPLYING MATRIX
a = np.array([ [1,2],[4,5] ])
b = np.array([ [7,8],[10,11] ])
c = np.add(a,b)

print(a)
print('\n')
print(b) 
print('\n')

#print(c)
#print('\n')

#THE SUM FUNCTION CAN BE USED TO ADD NUMBER IN 'A' MATRIX
#print(sum(a))

#MULTIPLICATION OF MATRIX
print(np.dot(a,b))
print('\n')
print(a*b)


[[1 2]
 [4 5]]


[[ 7  8]
 [10 11]]


[[27 30]
 [78 87]]


[[ 7 16]
 [40 55]]


In [18]:
#GETTING PRECISE NUMBER FROM MATRIX

es = np.array([ [1,2,3],[4,5,6],[7,8,9] ])
print(es)
print('\n')

print(es[:,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]


[3 6 9]


In [23]:
#CHECKING VALIDITY OF VALUES IN MATRIX
ea = np.array([ [1,2,3],[4,5,6] ])
print(ea)
print('\n')
print(ea < 4)


[[1 2 3]
 [4 5 6]]


[[ True  True  True]
 [False False False]]
